spring.application.name=driver-vehicle-service
server.port=8082

spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/ridelink_driver}

ridelink.security.jwt-secret=${JWT_SECRET:local-dev-only-change-this-secret-key-32b}
ridelink.security.internal-api-key=${INTERNAL_API_KEY:local-dev-internal-key}
ridelink.seed-demo-data=${SEED_DEMO_DATA:true}

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
