spring.application.name=ride-management-service
server.port=8083

spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/ridelink_ride}

ridelink.security.jwt-secret=${JWT_SECRET:local-dev-only-change-this-secret-key-32b}
ridelink.security.internal-api-key=${INTERNAL_API_KEY:local-dev-internal-key}

ridelink.services.account-url=${ACCOUNT_SERVICE_URL:http://localhost:8081}
ridelink.services.driver-url=${DRIVER_SERVICE_URL:http://localhost:8082}
ridelink.services.fare-url=${FARE_SERVICE_URL:http://localhost:8084}

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
