spring.application.name=account-service
server.port=8081

spring.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/ridelink_account}
spring.mongodb.database=ridelink_account
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/ridelink_account}
spring.data.mongodb.database=ridelink_account

ridelink.security.jwt-secret=${JWT_SECRET:local-dev-only-change-this-secret-key-32b}
ridelink.security.jwt-expiration-ms=${JWT_EXPIRATION_MS:86400000}
ridelink.security.internal-api-key=${INTERNAL_API_KEY:local-dev-internal-key}
ridelink.seed-demo-data=${SEED_DEMO_DATA:true}

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
