spring.application.name=fare-payment-service
server.port=8084

spring.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/ridelink_fare}
spring.mongodb.database=ridelink_fare
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/ridelink_fare}
spring.data.mongodb.database=ridelink_fare

ridelink.security.jwt-secret=${JWT_SECRET:local-dev-only-change-this-secret-key-32b}
ridelink.security.internal-api-key=${INTERNAL_API_KEY:local-dev-internal-key}

ridelink.fare.base-amount=150
ridelink.fare.per-km=80
ridelink.fare.per-minute=5
ridelink.fare.average-speed-kmh=30
ridelink.fare.currency=LKR

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
